apiVersion: v1
kind: Service
metadata:
  name: krci-cache
  labels:
    app.kubernetes.io/name: krci-cache
    app.kubernetes.io/component: cache-server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: krci-cache
    app.kubernetes.io/component: cache-server
